In [66]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\divya chauhan\appdata\roaming\python\python313\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\divya chauhan\appdata\roaming\python\python313\site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\divya chauhan\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\divya chauhan\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\divya chauhan\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\divya chauhan\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [67]:
import pandas as pd

In [68]:
df=pd.read_csv("spotify_millsongdata.csv")

In [69]:
df.head(5)

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [70]:
df.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [71]:
df.tail()

,artist,song,link,text
57644,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \r\nLet the angels fly...
57645,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \r\nMore power \r\nPowe...
57646,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \r\nis something i'll believe \...
57647,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \r\nam i frightened \r\nwhere ...
57648,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \r\nmake yourself at home \r\ni'm a ...

In [72]:
df.shape

(57649, 4)

In [73]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [74]:
df=df.sample(5000).drop('link',axis=1).reset_index(drop=True)

In [75]:
df.head()

,artist,song,text
0,Bryan White,How Lucky I Am,Standing in a field of three leaf clovers \r\...
1,Patsy Cline,Life's Railway To Heaven,Life is like a mountain railroad \r\nWith an ...
2,Uriah Heep,One Way Or Another,There's been some \r\nChanges in my time \r\...
3,Louis Armstrong,Way Down Yonder In New Orleans,Way down yonder in New Orleans \r\nIn the lan...
4,Kirk Franklin,Interlude,Interlude: Rebirth of Kirk Frankllin \r\n(Bac...

In [76]:
df['text'][0]

"Standing in a field of three leaf clovers  \r\nWaiting for the rain to pass over  \r\nNo rainbows, on my shoulder  \r\nJust the weight of walking day to day  \r\nNothing shiny coming along the way  \r\nThen I saw you and I reached out  \r\n(ain't) no more blue, now I understand why  \r\n  \r\nHow lucky I am lucky I am  \r\nTo be the one who fills your eyes  \r\nBlowin' away, sails on a lake  \r\nFlyin' like a flag in the sky  \r\nBright colored balloons in the wind  \r\nThat's how lucky I am  \r\n(how lucky I am)  \r\n  \r\nNow the road is rising up to meet me  \r\nAnd my half empty cup is filled completely  \r\nAnd I'm drinking that sweet taste of rain  \r\nSo grateful for each moment I get  \r\nTo have found you  \r\nI could have walked on by  \r\nBut the stars were on my side\r\n\r\n"

In [77]:
df.tail()

,artist,song,text
4995,Bee Gees,Jumbo,Jumbo said to say goodnight \r\nSee you in th...
4996,Judds,My Baby's Gone,I woke up this morning and the sun refused to ...
4997,Slayer,I Hate You,You were just a waste of sperm \r\nThey way y...
4998,Foo Fighters,The Colour And The Shape,"You're a real short ride, wow right \r\nIt'll..."
4999,High School Musical,"Right Here, Right Now",Hmm yea \r\nHey yea \r\n \r\nCan you imagin...

In [78]:
df['text']=df['text'].str.lower().replace(r'^\w\s',' ').replace(r'\n',' ',regex=True)

In [79]:
df['text']

0       standing in a field of three leaf clovers  \r ...
1       life is like a mountain railroad  \r with an e...
2       there's been some  \r changes in my time  \r b...
3       way down yonder in new orleans  \r in the land...
4       interlude: rebirth of kirk frankllin  \r (back...
                              ...
4995    jumbo said to say goodnight  \r see you in the...
4996    i woke up this morning and the sun refused to ...
4997    you were just a waste of sperm  \r they way yo...
4998    you're a real short ride, wow right  \r it'll ...
4999    hmm yea  \r hey yea  \r   \r can you imagine w...
Name: text, Length: 5000, dtype: object

In [80]:
df.tail()

,artist,song,text
4995,Bee Gees,Jumbo,jumbo said to say goodnight \r see you in the...
4996,Judds,My Baby's Gone,i woke up this morning and the sun refused to ...
4997,Slayer,I Hate You,you were just a waste of sperm \r they way yo...
4998,Foo Fighters,The Colour And The Shape,"you're a real short ride, wow right \r it'll ..."
4999,High School Musical,"Right Here, Right Now",hmm yea \r hey yea \r \r can you imagine w...

In [81]:
%pip install --upgrade nltk --quiet

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [82]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\Divya
[nltk_data]     Chauhan/nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [83]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

def token(text):
    tokens = word_tokenize(text)
    stemmed = [stemmer.stem(word) for word in tokens]
    return " ".join(stemmed)

In [84]:
print(token("You're beautifully dancing and enjoying every moment!"))

you 're beauti danc and enjoy everi moment !

In [85]:
token("you are beautiful,beautii")

'you are beauti , beautii'

In [86]:
df['text'].apply(lambda x: token(x))

0       stand in a field of three leaf clover wait for...
1       life is like a mountain railroad with an engin...
2       there 's been some chang in my time but thi on...
3       way down yonder in new orlean in the land of t...
4       interlud : rebirth of kirk frankllin ( backgro...
                              ...
4995    jumbo said to say goodnight see you in the mor...
4996    i woke up thi morn and the sun refus to shine ...
4997    you were just a wast of sperm they way you loo...
4998    you 're a real short ride , wow right it 'll b...
4999    hmm yea hey yea can you imagin what would happ...
Name: text, Length: 5000, dtype: object

In [87]:
%pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\divya chauhan\appdata\roaming\python\python313\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\divya chauhan\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.2.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\divya chauhan\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\divya chauhan\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\divya chauhan\appdata\roaming\python\python313\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [88]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [89]:
Tfid=TfidfVectorizer(analyzer='word',stop_words='english')

In [90]:
matrix = Tfid.fit_transform(df['text'])

In [91]:
similar=cosine_similarity(matrix)

In [92]:
similar[0]

array([1.        , 0.02195007, 0.0344951 , ..., 0.03326865, 0.01016069,
       0.03022347], shape=(5000,))

In [93]:
df[df['song']=="Start A New Life"]

Empty DataFrame
Columns: [artist, song, text]
Index: []

In [94]:
df[df['song'].str.strip().str.lower() == "Start A New Life".lower()]

Empty DataFrame
Columns: [artist, song, text]
Index: []

In [95]:
index = df[df['song'].str.strip().str.lower() == "Start A New Life".lower()].index

if not index.empty:
    print(index[0])
else:
    print("Song not found")

Song not found

In [96]:
def recommender(song_name):
    # Normalize and match song name (case-insensitive and trimmed)
    idx_match = df[df['song'].str.strip().str.lower() == song_name.strip().lower()].index

    # Check if song was found
    if idx_match.empty:
        return ["Song not found in dataset."]
    
    idx = idx_match[0]

    distance = sorted(
        list(enumerate(similar[idx])),
        reverse=True,
        key=lambda x: x[1]
    )

    song = []
    for s_id in distance[1:6]:  # Skip first one as it is the song itself
        song.append(df.iloc[s_id[0]]['song'])

    return song

In [97]:
recommender("Start A New Life")

['Song not found in dataset.']

In [98]:
recommender("America, The Beautiful")

['Song not found in dataset.']

In [99]:
import pickle

In [100]:
pickle.dump(similar, open("similarity","wb"))

In [101]:
pickle.dump(df,open("df","wb"))